// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: grpc/tradeapi/v1/trade.proto

package v1

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Информация о сделке
type AccountTrade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор сделки
	TradeId string `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	// Символ инструмента
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Цена исполнения
	Price *decimal.Decimal `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// Размер в шт.
	Size *decimal.Decimal `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	// Сторона сделки (long или short)
	Side Side `protobuf:"varint,5,opt,name=side,proto3,enum=grpc.tradeapi.v1.Side" json:"side,omitempty"`
	// Метка времени
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Идентификатор заявки
	OrderId string `protobuf:"bytes,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Идентификатор аккаунта
	AccountId string `protobuf:"bytes,8,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Метка заявки. (максимум 128 символов)
	Comment string `protobuf:"bytes,9,opt,name=comment,proto3" json:"comment,omitempty"`
	// НКД (заполняется на следующий день после даты совершения сделки)
	AccruedInterest *decimal.Decimal `protobuf:"bytes,10,opt,name=accrued_interest,json=accruedInterest,proto3" json:"accrued_interest,omitempty"`
	// Валюта цены (например, RUB, USD, EUR)
	// Примечание: поле заполняется только при использовании метода Trades
	// Для SubscribeTrades данное поле может быть пустым в связи с различиями в источниках данных. При обработке сделок из подписки рекомендуется учитывать возможность пустого значения.
	Currency string `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	// Комиссия. Заполняется для исторических сделок
	Commission    *AccountTrade_Commission `protobuf:"bytes,12,opt,name=commission,proto3" json:"commission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountTrade) Reset() {
	*x = AccountTrade{}
	mi := &file_grpc_tradeapi_v1_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTrade) ProtoMessage() {}

func (x *AccountTrade) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTrade.ProtoReflect.Descriptor instead.
func (*AccountTrade) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_trade_proto_rawDescGZIP(), []int{0}
}

func (x *AccountTrade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *AccountTrade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AccountTrade) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *AccountTrade) GetSize() *decimal.Decimal {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *AccountTrade) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *AccountTrade) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AccountTrade) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AccountTrade) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountTrade) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AccountTrade) GetAccruedInterest() *decimal.Decimal {
	if x != nil {
		return x.AccruedInterest
	}
	return nil
}

func (x *AccountTrade) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountTrade) GetCommission() *AccountTrade_Commission {
	if x != nil {
		return x.Commission
	}
	return nil
}

// Комиссия по сделке
type AccountTrade_Commission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Значение комиссии
	Value *decimal.Decimal `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Валюта комиссии
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountTrade_Commission) Reset() {
	*x = AccountTrade_Commission{}
	mi := &file_grpc_tradeapi_v1_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTrade_Commission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTrade_Commission) ProtoMessage() {}

func (x *AccountTrade_Commission) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTrade_Commission.ProtoReflect.Descriptor instead.
func (*AccountTrade_Commission) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_trade_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AccountTrade_Commission) GetValue() *decimal.Decimal {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AccountTrade_Commission) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_grpc_tradeapi_v1_trade_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_trade_proto_rawDesc = "" +
	"\n" +
	"\x1cgrpc/tradeapi/v1/trade.proto\x12\x10grpc.tradeapi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/type/decimal.proto\x1a\x1bgrpc/tradeapi/v1/side.proto\"\xcf\x04\n" +
	"\fAccountTrade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12*\n" +
	"\x05price\x18\x03 \x01(\v2\x14.google.type.DecimalR\x05price\x12(\n" +
	"\x04size\x18\x04 \x01(\v2\x14.google.type.DecimalR\x04size\x12*\n" +
	"\x04side\x18\x05 \x01(\x0e2\x16.grpc.tradeapi.v1.SideR\x04side\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\border_id\x18\a \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"account_id\x18\b \x01(\tR\taccountId\x12\x18\n" +
	"\acomment\x18\t \x01(\tR\acomment\x12?\n" +
	"\x10accrued_interest\x18\n" +
	" \x01(\v2\x14.google.type.DecimalR\x0faccruedInterest\x12\x1a\n" +
	"\bcurrency\x18\v \x01(\tR\bcurrency\x12I\n" +
	"\n" +
	"commission\x18\f \x01(\v2).grpc.tradeapi.v1.AccountTrade.CommissionR\n" +
	"commission\x1aT\n" +
	"\n" +
	"Commission\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.type.DecimalR\x05value\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrencyB;P\x01Z7github.com/FinamWeb/finam-trade-api/go/grpc/tradeapi/v1b\x06proto3"

var (
	file_grpc_tradeapi_v1_trade_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_trade_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_trade_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_trade_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_trade_proto_rawDesc), len(file_grpc_tradeapi_v1_trade_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_trade_proto_rawDescData
}

var file_grpc_tradeapi_v1_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_tradeapi_v1_trade_proto_goTypes = []any{
	(*AccountTrade)(nil),            // 0: grpc.tradeapi.v1.AccountTrade
	(*AccountTrade_Commission)(nil), // 1: grpc.tradeapi.v1.AccountTrade.Commission
	(*decimal.Decimal)(nil),         // 2: google.type.Decimal
	(Side)(0),                       // 3: grpc.tradeapi.v1.Side
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_grpc_tradeapi_v1_trade_proto_depIdxs = []int32{
	2, // 0: grpc.tradeapi.v1.AccountTrade.price:type_name -> google.type.Decimal
	2, // 1: grpc.tradeapi.v1.AccountTrade.size:type_name -> google.type.Decimal
	3, // 2: grpc.tradeapi.v1.AccountTrade.side:type_name -> grpc.tradeapi.v1.Side
	4, // 3: grpc.tradeapi.v1.AccountTrade.timestamp:type_name -> google.protobuf.Timestamp
	2, // 4: grpc.tradeapi.v1.AccountTrade.accrued_interest:type_name -> google.type.Decimal
	1, // 5: grpc.tradeapi.v1.AccountTrade.commission:type_name -> grpc.tradeapi.v1.AccountTrade.Commission
	2, // 6: grpc.tradeapi.v1.AccountTrade.Commission.value:type_name -> google.type.Decimal
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_trade_proto_init() }
func file_grpc_tradeapi_v1_trade_proto_init() {
	if File_grpc_tradeapi_v1_trade_proto != nil {
		return
	}
	file_grpc_tradeapi_v1_side_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_trade_proto_rawDesc), len(file_grpc_tradeapi_v1_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_tradeapi_v1_trade_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_trade_proto_depIdxs,
		MessageInfos:      file_grpc_tradeapi_v1_trade_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_trade_proto = out.File
	file_grpc_tradeapi_v1_trade_proto_goTypes = nil
	file_grpc_tradeapi_v1_trade_proto_depIdxs = nil
}
