// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: grpc/tradeapi/v1/reports/reports_service.proto

package reports

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Форма отчета
type ReportForm int32

const (
	// Не указана
	ReportForm_REPORT_FORM_UNKNOWN ReportForm = 0
	// Краткая
	ReportForm_REPORT_FORM_SHORT ReportForm = 1
	// Полная
	ReportForm_REPORT_FORM_LONG ReportForm = 2
)

// Enum value maps for ReportForm.
var (
	ReportForm_name = map[int32]string{
		0: "REPORT_FORM_UNKNOWN",
		1: "REPORT_FORM_SHORT",
		2: "REPORT_FORM_LONG",
	}
	ReportForm_value = map[string]int32{
		"REPORT_FORM_UNKNOWN": 0,
		"REPORT_FORM_SHORT":   1,
		"REPORT_FORM_LONG":    2,
	}
)

func (x ReportForm) Enum() *ReportForm {
	p := new(ReportForm)
	*p = x
	return p
}

func (x ReportForm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportForm) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_enumTypes[0].Descriptor()
}

func (ReportForm) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_reports_reports_service_proto_enumTypes[0]
}

func (x ReportForm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportForm.Descriptor instead.
func (ReportForm) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{0}
}

// Статус генерации отчёта
type ReportCreationStatus int32

const (
	// Не найден
	ReportCreationStatus_NOT_FOUND ReportCreationStatus = 0
	// Ожидает генерации
	ReportCreationStatus_PENDING ReportCreationStatus = 1
	// Генерация запущена
	ReportCreationStatus_IN_PROGRESS ReportCreationStatus = 2
	// Генерация завершена успешно
	ReportCreationStatus_SUCCESS ReportCreationStatus = 3
	// Генерация завершена с ошибкой
	ReportCreationStatus_ERROR ReportCreationStatus = 4
)

// Enum value maps for ReportCreationStatus.
var (
	ReportCreationStatus_name = map[int32]string{
		0: "NOT_FOUND",
		1: "PENDING",
		2: "IN_PROGRESS",
		3: "SUCCESS",
		4: "ERROR",
	}
	ReportCreationStatus_value = map[string]int32{
		"NOT_FOUND":   0,
		"PENDING":     1,
		"IN_PROGRESS": 2,
		"SUCCESS":     3,
		"ERROR":       4,
	}
)

func (x ReportCreationStatus) Enum() *ReportCreationStatus {
	p := new(ReportCreationStatus)
	*p = x
	return p
}

func (x ReportCreationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportCreationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_enumTypes[1].Descriptor()
}

func (ReportCreationStatus) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_reports_reports_service_proto_enumTypes[1]
}

func (x ReportCreationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportCreationStatus.Descriptor instead.
func (ReportCreationStatus) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{1}
}

// Запрос на генерацию отчёта по счёту за период
type CreateAccountReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Временной интервал. Максимальный интервал дат - 92 дня
	DateRange *DateRange `protobuf:"bytes,1,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	// Форма отчета
	ReportForm ReportForm `protobuf:"varint,2,opt,name=report_form,json=reportForm,proto3,enum=grpc.tradeapi.v1.reports.ReportForm" json:"report_form,omitempty"`
	// Идентификатор счета
	AccountId     int64 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountReportRequest) Reset() {
	*x = CreateAccountReportRequest{}
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReportRequest) ProtoMessage() {}

func (x *CreateAccountReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReportRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountReportRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountReportRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *CreateAccountReportRequest) GetReportForm() ReportForm {
	if x != nil {
		return x.ReportForm
	}
	return ReportForm_REPORT_FORM_UNKNOWN
}

func (x *CreateAccountReportRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// Информация о генерируемом отчёте
type CreateAccountReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор отчёта
	ReportId      string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountReportResponse) Reset() {
	*x = CreateAccountReportResponse{}
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReportResponse) ProtoMessage() {}

func (x *CreateAccountReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReportResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountReportResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

// Запрос на получение статуса генерации отчёта
type GetAccountReportInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор отчёта
	ReportId      string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountReportInfoRequest) Reset() {
	*x = GetAccountReportInfoRequest{}
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountReportInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountReportInfoRequest) ProtoMessage() {}

func (x *GetAccountReportInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountReportInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAccountReportInfoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountReportInfoRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

// Информация о статусе генерации отчёта
type GetAccountReportInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация о статусе генерации отчёта
	Info          *AccountReportInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountReportInfoResponse) Reset() {
	*x = GetAccountReportInfoResponse{}
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountReportInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountReportInfoResponse) ProtoMessage() {}

func (x *GetAccountReportInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountReportInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAccountReportInfoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountReportInfoResponse) GetInfo() *AccountReportInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// Запрос подписки на получение статуса генерации отчёта
type SubscribeAccountReportInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор отчёта
	ReportId      string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAccountReportInfoRequest) Reset() {
	*x = SubscribeAccountReportInfoRequest{}
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountReportInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountReportInfoRequest) ProtoMessage() {}

func (x *SubscribeAccountReportInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountReportInfoRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAccountReportInfoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeAccountReportInfoRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

// Информация о статусе генерации отчёта. Стрим
type SubscribeAccountReportInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация о статусе генерации отчёта
	Info          *AccountReportInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAccountReportInfoResponse) Reset() {
	*x = SubscribeAccountReportInfoResponse{}
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountReportInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountReportInfoResponse) ProtoMessage() {}

func (x *SubscribeAccountReportInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountReportInfoResponse.ProtoReflect.Descriptor instead.
func (*SubscribeAccountReportInfoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeAccountReportInfoResponse) GetInfo() *AccountReportInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// Информация о статусе генерации отчёта
type AccountReportInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор отчёта
	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// Статус генерации отчёта
	Status ReportCreationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=grpc.tradeapi.v1.reports.ReportCreationStatus" json:"status,omitempty"`
	// Временной интервал отчёта. Берётся из запроса на генерацию отчёта
	DateRange *DateRange `protobuf:"bytes,3,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	// Форма отчета. Берётся из запроса на генерацию отчёта
	ReportForm ReportForm `protobuf:"varint,4,opt,name=report_form,json=reportForm,proto3,enum=grpc.tradeapi.v1.reports.ReportForm" json:"report_form,omitempty"`
	// Идентификатор счета. Берётся из запроса на генерацию отчёта
	AccountId int64 `protobuf:"varint,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Ссылка на скачивание отчёта. Появляется только в случае успешной генерации отчёта (ReportCreationStatus = SUCCESS)
	Url           *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountReportInfo) Reset() {
	*x = AccountReportInfo{}
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountReportInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReportInfo) ProtoMessage() {}

func (x *AccountReportInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReportInfo.ProtoReflect.Descriptor instead.
func (*AccountReportInfo) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{6}
}

func (x *AccountReportInfo) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AccountReportInfo) GetStatus() ReportCreationStatus {
	if x != nil {
		return x.Status
	}
	return ReportCreationStatus_NOT_FOUND
}

func (x *AccountReportInfo) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *AccountReportInfo) GetReportForm() ReportForm {
	if x != nil {
		return x.ReportForm
	}
	return ReportForm_REPORT_FORM_UNKNOWN
}

func (x *AccountReportInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountReportInfo) GetUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.Url
	}
	return nil
}

// Временной интервал
type DateRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Дата начала временного интервала
	DateBegin *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date_begin,json=dateBegin,proto3" json:"date_begin,omitempty"`
	// Дата конца временного интервала
	DateEnd       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_end,json=dateEnd,proto3" json:"date_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP(), []int{7}
}

func (x *DateRange) GetDateBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.DateBegin
	}
	return nil
}

func (x *DateRange) GetDateEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.DateEnd
	}
	return nil
}

var File_grpc_tradeapi_v1_reports_reports_service_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_reports_reports_service_proto_rawDesc = "" +
	"\n" +
	".grpc/tradeapi/v1/reports/reports_service.proto\x12\x18grpc.tradeapi.v1.reports\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a;grpc/gateway/protoc_gen_openapiv2/options/annotations.proto\"\xc6\x01\n" +
	"\x1aCreateAccountReportRequest\x12B\n" +
	"\n" +
	"date_range\x18\x01 \x01(\v2#.grpc.tradeapi.v1.reports.DateRangeR\tdateRange\x12E\n" +
	"\vreport_form\x18\x02 \x01(\x0e2$.grpc.tradeapi.v1.reports.ReportFormR\n" +
	"reportForm\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\":\n" +
	"\x1bCreateAccountReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\":\n" +
	"\x1bGetAccountReportInfoRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"_\n" +
	"\x1cGetAccountReportInfoResponse\x12?\n" +
	"\x04info\x18\x01 \x01(\v2+.grpc.tradeapi.v1.reports.AccountReportInfoR\x04info\"@\n" +
	"!SubscribeAccountReportInfoRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"e\n" +
	"\"SubscribeAccountReportInfoResponse\x12?\n" +
	"\x04info\x18\x01 \x01(\v2+.grpc.tradeapi.v1.reports.AccountReportInfoR\x04info\"\xd2\x02\n" +
	"\x11AccountReportInfo\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12F\n" +
	"\x06status\x18\x02 \x01(\x0e2..grpc.tradeapi.v1.reports.ReportCreationStatusR\x06status\x12B\n" +
	"\n" +
	"date_range\x18\x03 \x01(\v2#.grpc.tradeapi.v1.reports.DateRangeR\tdateRange\x12E\n" +
	"\vreport_form\x18\x04 \x01(\x0e2$.grpc.tradeapi.v1.reports.ReportFormR\n" +
	"reportForm\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\x03R\taccountId\x12.\n" +
	"\x03url\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x03url\"}\n" +
	"\tDateRange\x129\n" +
	"\n" +
	"date_begin\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tdateBegin\x125\n" +
	"\bdate_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\adateEnd*R\n" +
	"\n" +
	"ReportForm\x12\x17\n" +
	"\x13REPORT_FORM_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11REPORT_FORM_SHORT\x10\x01\x12\x14\n" +
	"\x10REPORT_FORM_LONG\x10\x02*[\n" +
	"\x14ReportCreationStatus\x12\r\n" +
	"\tNOT_FOUND\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xa5\x04\n" +
	"\x0eReportsService\x12\xb1\x01\n" +
	"\x13CreateAccountReport\x124.grpc.tradeapi.v1.reports.CreateAccountReportRequest\x1a5.grpc.tradeapi.v1.reports.CreateAccountReportResponse\"-\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/report\x12\xc2\x01\n" +
	"\x14GetAccountReportInfo\x125.grpc.tradeapi.v1.reports.GetAccountReportInfoRequest\x1a6.grpc.tradeapi.v1.reports.GetAccountReportInfoResponse\";\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/report/{report_id}/info\x12\x99\x01\n" +
	"\x1aSubscribeAccountReportInfo\x12;.grpc.tradeapi.v1.reports.SubscribeAccountReportInfoRequest\x1a<.grpc.tradeapi.v1.reports.SubscribeAccountReportInfoResponse0\x01B\xc2\x05\x92A\xfb\x04\x12?\n" +
	"\x0fFinam Trade-API\x12,API для торговых операций*\x02\x01\x02Ri\n" +
	"\x03401\x12b\n" +
	"`Срок действия токена истек или токен недействителенR6\n" +
	"\x03429\x12/\n" +
	"-Превышен лимит запросов.RZ\n" +
	"\x03500\x12S\n" +
	"QВнутренняя ошибка сервиса. Попробуйте позжеRk\n" +
	"\x03503\x12d\n" +
	"bСервис на данный момент не доступен. Попробуйте позжеRV\n" +
	"\x03504\x12O\n" +
	"MКрайний срок истек до завершения операцииR!\n" +
	"\adefault\x12\x16\x12\x14\n" +
	"\x12\x1a\x10googletypeStatusZM\n" +
	"K\n" +
	"\rAuthorization\x12:\b\x02\x12%JWT токен авторизации\x1a\rAuthorization \x02P\x01Z?github.com/FinamWeb/finam-trade-api/go/grpc/tradeapi/v1/reportsb\x06proto3"

var (
	file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_reports_reports_service_proto_rawDesc), len(file_grpc_tradeapi_v1_reports_reports_service_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_reports_reports_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_reports_reports_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_tradeapi_v1_reports_reports_service_proto_goTypes = []any{
	(ReportForm)(0),                            // 0: grpc.tradeapi.v1.reports.ReportForm
	(ReportCreationStatus)(0),                  // 1: grpc.tradeapi.v1.reports.ReportCreationStatus
	(*CreateAccountReportRequest)(nil),         // 2: grpc.tradeapi.v1.reports.CreateAccountReportRequest
	(*CreateAccountReportResponse)(nil),        // 3: grpc.tradeapi.v1.reports.CreateAccountReportResponse
	(*GetAccountReportInfoRequest)(nil),        // 4: grpc.tradeapi.v1.reports.GetAccountReportInfoRequest
	(*GetAccountReportInfoResponse)(nil),       // 5: grpc.tradeapi.v1.reports.GetAccountReportInfoResponse
	(*SubscribeAccountReportInfoRequest)(nil),  // 6: grpc.tradeapi.v1.reports.SubscribeAccountReportInfoRequest
	(*SubscribeAccountReportInfoResponse)(nil), // 7: grpc.tradeapi.v1.reports.SubscribeAccountReportInfoResponse
	(*AccountReportInfo)(nil),                  // 8: grpc.tradeapi.v1.reports.AccountReportInfo
	(*DateRange)(nil),                          // 9: grpc.tradeapi.v1.reports.DateRange
	(*wrapperspb.StringValue)(nil),             // 10: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),              // 11: google.protobuf.Timestamp
}
var file_grpc_tradeapi_v1_reports_reports_service_proto_depIdxs = []int32{
	9,  // 0: grpc.tradeapi.v1.reports.CreateAccountReportRequest.date_range:type_name -> grpc.tradeapi.v1.reports.DateRange
	0,  // 1: grpc.tradeapi.v1.reports.CreateAccountReportRequest.report_form:type_name -> grpc.tradeapi.v1.reports.ReportForm
	8,  // 2: grpc.tradeapi.v1.reports.GetAccountReportInfoResponse.info:type_name -> grpc.tradeapi.v1.reports.AccountReportInfo
	8,  // 3: grpc.tradeapi.v1.reports.SubscribeAccountReportInfoResponse.info:type_name -> grpc.tradeapi.v1.reports.AccountReportInfo
	1,  // 4: grpc.tradeapi.v1.reports.AccountReportInfo.status:type_name -> grpc.tradeapi.v1.reports.ReportCreationStatus
	9,  // 5: grpc.tradeapi.v1.reports.AccountReportInfo.date_range:type_name -> grpc.tradeapi.v1.reports.DateRange
	0,  // 6: grpc.tradeapi.v1.reports.AccountReportInfo.report_form:type_name -> grpc.tradeapi.v1.reports.ReportForm
	10, // 7: grpc.tradeapi.v1.reports.AccountReportInfo.url:type_name -> google.protobuf.StringValue
	11, // 8: grpc.tradeapi.v1.reports.DateRange.date_begin:type_name -> google.protobuf.Timestamp
	11, // 9: grpc.tradeapi.v1.reports.DateRange.date_end:type_name -> google.protobuf.Timestamp
	2,  // 10: grpc.tradeapi.v1.reports.ReportsService.CreateAccountReport:input_type -> grpc.tradeapi.v1.reports.CreateAccountReportRequest
	4,  // 11: grpc.tradeapi.v1.reports.ReportsService.GetAccountReportInfo:input_type -> grpc.tradeapi.v1.reports.GetAccountReportInfoRequest
	6,  // 12: grpc.tradeapi.v1.reports.ReportsService.SubscribeAccountReportInfo:input_type -> grpc.tradeapi.v1.reports.SubscribeAccountReportInfoRequest
	3,  // 13: grpc.tradeapi.v1.reports.ReportsService.CreateAccountReport:output_type -> grpc.tradeapi.v1.reports.CreateAccountReportResponse
	5,  // 14: grpc.tradeapi.v1.reports.ReportsService.GetAccountReportInfo:output_type -> grpc.tradeapi.v1.reports.GetAccountReportInfoResponse
	7,  // 15: grpc.tradeapi.v1.reports.ReportsService.SubscribeAccountReportInfo:output_type -> grpc.tradeapi.v1.reports.SubscribeAccountReportInfoResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_reports_reports_service_proto_init() }
func file_grpc_tradeapi_v1_reports_reports_service_proto_init() {
	if File_grpc_tradeapi_v1_reports_reports_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_reports_reports_service_proto_rawDesc), len(file_grpc_tradeapi_v1_reports_reports_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_reports_reports_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_reports_reports_service_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_reports_reports_service_proto_enumTypes,
		MessageInfos:      file_grpc_tradeapi_v1_reports_reports_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_reports_reports_service_proto = out.File
	file_grpc_tradeapi_v1_reports_reports_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_reports_reports_service_proto_depIdxs = nil
}
